apiVersion: v2
name: ember
description: a low-latency, memory-efficient distributed cache
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - cache
  - redis
  - distributed
  - rust
  - kv
