{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ember.serviceAccountName" . }}
  labels:
    {{- include "ember.labels" . | nindent 4 }}
{{- end }}
