apiVersion: v1
kind: Service
metadata:
  name: {{ include "ember.fullname" . }}
  labels:
    {{- include "ember.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: cache
      protocol: TCP
      name: cache
    {{- if .Values.ember.metricsPort }}
    - port: {{ .Values.ember.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "ember.selectorLabels" . | nindent 4 }}
